name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        run: git pull
        working-directory: ../../next-json-webtool/next-json-webtool

      - name: Install Dependencies
        run: npm install
        working-directory: ../../next-json-webtool/next-json-webtool

      - name: Build
        run: npm run build
        working-directory: ../../next-json-webtool/next-json-webtool

      - name: Restart Server
        run: pm2 restart all
