name: Auto Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: VM-4-6-ubuntu]
    steps:
      - name: Checkout Code
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Restart Server
        run: pm2 restart all
