name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ../../next-json-webtool/next-json-webtool
    steps:
      - name: Checkout Code
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Restart Server
        run: pm2 restart all
