name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        run: sudo git pull
        working-directory: /home/ubuntu/next-json-webtool/next-json-webtool # 指定你的项目路径

      # - name: Install Dependencies
      #   run: npm install
      #   working-directory: /home/ubuntu/next-json-webtool/next-json-webtool # 指定你的项目路径

      - name: Build
        run: npm run build
        working-directory: /home/ubuntu/next-json-webtool/next-json-webtool # 指定你的项目路径

      - name: Restart Server
        run: sudo pm2 restart all
